name: 'Next Release Version'
description: 'Find the Semantic Version for the next release based on branch name and existing releases'
branding:
  icon: 'arrow-up-circle'
  color: 'blue'
inputs:
  repo:
    description: 'The repository name'
    default: ${{ github.repository }}
    required: false
  username:
    description: 'GitHub username'
    default: ${{ github.repository_owner }}
    required: false
  token:
    description: 'GitHub token'
    required: true
  branch:
    description: 'The current branch'
    default: ${{ github.ref }}
    required: false
  projects:
    description: 'The Project Type (Single or Multi)'
    required: false
    default: 'Single'
  prefix:
    description: 'A prefix to all versions'
    required: false
    default: 'v'
outputs:
  next-version:
    description: 'The next semantic version for the next release without prefix'
  next-version-name:
    description: 'The next semantic version for the next release with prefix'
  folder:
    description: 'The name of the folder for the branch'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - --repo
    - ${{ inputs.repo }}
    - --username
    - ${{ inputs.username }}
    - --token
    - ${{ inputs.token }}
    - --branch
    - ${{ inputs.branch }}
    - --projects
    - ${{ inputs.projects }}
    - --prefix
    - ${{ inputs.prefix }}
